### PR TITLE
(CAT-1521) - Adding new OS RHEL-9 ARM

### PR DESCRIPTION
**Pull request by Ramesh7**
## Summary
Agent Team have certified puppet agent with FOSS RHEL-9-ARM so we need to add for module testing as well.

## Additional Context
- [x] Adding RHEL-9-ARM in litmus

## Related Issues (if any)
N/A

## Checklist
- [x] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [x] Manually verified.

### CODE REVIEW

**Review by malikparvez — APPROVED** [review]
lgtm

**Comment by GSPatton** [comment]
@Ramesh7 would matrix_from_metadata also need updated? https://github.com/puppetlabs/puppet_litmus/blob/affb26deca645ee9059b2f968189fe672c952298/exe/matrix_from_metadata_v2#L30 

also, it would be good to add a spec test for this here: https://github.com/puppetlabs/puppet_litmus/blob/main/spec/exe/matrix_from_metadata_v2_spec.rb

**Comment by Ramesh7** [comment]
> matrix_from_metadata_v2_spec.rb

Thanks @GSPatton for review, have addressed the comments, ready to re-review.

**Review by jordanbreen28 — APPROVED** [review]
Nice one @Ramesh7. Tested this using the values from `matrix_from_metadata_v2` and it all seems to work.
I'll kick off the release job.

**Pull request merged**
