### PR TITLE
(maint) 0.7.2 release prep

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
Successful on 24 nodes: ["g57x3rpnn1gjw3z.delivery.puppetlabs.net, sles-11-x86_64", "h6v9pl48pn15f76.delivery.puppetlabs.net, ubuntu-1804-x86_64", "ya0luh4uer18dji.delivery.puppetlabs.net, ubuntu-1604-x86_64", "y5qdsbn1ar5m4du.delivery.puppetlabs.net, centos-6-x86_64", "wagclbqktrs6137.delivery.puppetlabs.net, sles-12-x86_64", "qx9mx4zhrclcbo3.delivery.puppetlabs.net, centos-7-x86_64", "o15q4vdmr5042q3.delivery.puppetlabs.net, oracle-7-x86_64", "b4dncurk0fcjlco.delivery.puppetlabs.net, oracle-6-x86_64", "kdjrlynfq2afo2p.delivery.puppetlabs.net, redhat-8-x86_64", "dzzyukyvvfrp0zi.delivery.puppetlabs.net, redhat-7-x86_64", "vlsssjmq3jhhd4c.delivery.puppetlabs.net, ubuntu-1404-x86_64", "sq06vufylqyj2g4.delivery.puppetlabs.net, scientific-7-x86_64", "sq0we9b0ppdfqyf.delivery.puppetlabs.net, scientific-6-x86_64", "s4n0rl82yj37c9l.delivery.puppetlabs.net, redhat-6-x86_64", "cgn6d6arg773iq7.delivery.puppetlabs.net, redhat-5-x86_64", "d27xdtsrp8cpg83.delivery.puppetlabs.net, sles-15-x86_64", "up9ds4dim3if961.delivery.puppetlabs.net, centos-5-x86_64", "w5keus4s2d24zhg.delivery.puppetlabs.net, oracle-5-x86_64", "eir6he0zhw7p5hu.delivery.puppetlabs.net, debian-9-x86_64", "sf2e80nsum5sbmw.delivery.puppetlabs.net, debian-8-x86_64", "nlscnn3vr4b9yvt.delivery.puppetlabs.net, win-2016-x86_64", "moz24p54evbn927.delivery.puppetlabs.net, win-2012r2-x86_64", "kcv5up15bqe7bwo.delivery.puppetlabs.net, win-2008r2-x86_64", "y8p7bs87bdy59t3.delivery.puppetlabs.net, win-10-pro-x86_64"] successful for motd

**Comment by tphoney** [comment]
puppetlabs-scheduled_task git:(master) ✗ TARGET_HOST=fnnas3rxlo1rdj2.delivery.puppetlabs.net bundle exec rspec spec/litmus/

Should create a scheduled task
  Should create a task if it does not exist: taskscheduler_api2
  Should create a task if it does not exist: win32_taskscheduler
  Should create a task with a username and password: taskscheduler_api2
  Should create a task with a username and password: win32_taskscheduler
  Should update a task's credentials: win32_taskscheduler
  Should update a task's credentials: taskscheduler_api2

Should destroy a scheduled task
  Should destroy the task

Finished in 3 minutes 39.4 seconds (files took 1.08 seconds to load)
7 examples, 0 failures
puppetlabs-scheduled_task passing

**Comment by sheenaajay** [comment]
bundle exec rake litmus:acceptance:axnbgidnyeuinek.delivery.puppetlabs.net
/Users/sheena/.rvm/rubies/ruby-2.5.3/bin/ruby -I/Users/sheena/repos/litmus/newchanges/puppetlabs-package/.bundle/gems/ruby/2.5.0/gems/rspec-core-3.8.2/lib:/Users/sheena/repos/litmus/newchanges/puppetlabs-package/.bundle/gems/ruby/2.5.0/gems/rspec-support-3.8.2/lib /Users/sheena/repos/litmus/newchanges/puppetlabs-package/.bundle/gems/ruby/2.5.0/gems/rspec-core-3.8.2/exe/rspec --pattern spec/acceptance/\*\*\{,/\*/\*\*\}/\*_spec.rb

package task
  uninstall
    uninstalls pry
    status

windows package task
  install action
    install notepadplusplus.install
  uninstall action
    uninstall notepadplusplus.install
  install specific
    upgrade notepad++ to a specific version
    upgrade notepad++
  when puppet-agent feature not available on target
    status action fails

Finished in 3 minutes 0.9 seconds (files took 0.97672 seconds to load)
7 examples, 0 failures

**Comment by tphoney** [comment]
also for completeness:
Successful on 19 nodes: ["dhiacp2q1974pcl.delivery.puppetlabs.net, scientific-6-x86_64", "bc2lshcw5slmjgd.delivery.puppetlabs.net, redhat-6-x86_64", "ysgp4tg6cden59m.delivery.puppetlabs.net, centos-6-x86_64", "w3gw842nn3s2t6v.delivery.puppetlabs.net, oracle-6-x86_64", "b3ak3b7ju71v2pf.delivery.puppetlabs.net, ubuntu-1604-x86_64", "nzezwcipu5ah2ah.delivery.puppetlabs.net, oracle-7-x86_64", "kgl65ers92yvkau.delivery.puppetlabs.net, scientific-7-x86_64", "lom3r6zls718hjo.delivery.puppetlabs.net, ubuntu-1804-x86_64", "n385w0d7yfnm135.delivery.puppetlabs.net, debian-8-x86_64", "y9h44tfhjleielm.delivery.puppetlabs.net, centos-7-x86_64", "rt6hy53wjy2v7gb.delivery.puppetlabs.net, ubuntu-1404-x86_64", "pyywh20flelh6yo.delivery.puppetlabs.net, debian-9-x86_64", "txsjaik63r2krjo.delivery.puppetlabs.net, redhat-8-x86_64", "pzfy80hlqvrvmv1.delivery.puppetlabs.net, redhat-5-x86_64", "dij8suu7qbap6o8.delivery.puppetlabs.net, redhat-7-x86_64", "u62gph7s0smkri0.delivery.puppetlabs.net, oracle-5-x86_64", "dmv2bfw2u4m9dlp.delivery.puppetlabs.net, win-2016-x86_64", "th2pcsupua4j6as.delivery.puppetlabs.net, win-2019-x86_64", "bdy2skx20s67apr.delivery.puppetlabs.net, win-10-pro-x86_64"]
Failed on 4 nodes: ["ojglqd9qyecjmio.delivery.puppetlabs.net, centos-5-x86_64", "rlfxq1l3i9uxbxk.delivery.puppetlabs.net, win-2012r2-x86_64", "b39sniyesxv5nbs.delivery.puppetlabs.net, win-10-pro-x86_64", "kq561zouwmvm31q.delivery.puppetlabs.net, win-2008r2-x86_64"]

**Pull request merged**
