### PR TITLE
(bugfix) Handle expect_failures case correct

### PR DESCRIPTION
**Pull request by hajee**
Let litmus raise and error if an error was expected but not received (Like option n beaker)

### CODE REVIEW

**Comment by florindragos** [comment]
Hi @hajee,
Could you please rebase? 
Thanks!

**Comment by hajee** [comment]
Done

**Comment by hajee** [comment]
Could you please evaluate before another rebase is required ;-)

**Comment by florindragos** [comment]
Hey @hajee, we're in the process of fixing the expect/catch changes/failures in #185

**Comment by hajee** [comment]
Ok Thanks for the heads up. Shall I close this one then?

**Pull request closed without merging**
