### PR TITLE
0.9.1 release prep

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
Following https://confluence.puppetlabs.com/pages/viewpage.action?spaceKey=ECO&title=litmus+release+processes

**Comment by michaeltlombardi** [comment]
@tphoney should this go to release rather than master?

**Comment by tphoney** [comment]
nope, gems you just merge to master then tag. 
we still need to test this branch, similar  to what i did for 0.9.0

https://github.com/puppetlabs/puppet_litmus/pull/174

**Comment by michaeltlombardi** [comment]
image

**Comment by michaeltlombardi** [comment]
image

**Pull request merged**
